apiVersion: v1
kind: Pod
metadata:
  name: backbase-banking-jenkins-pod
  labels:
    jenkins: aws
spec:
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock

  containers:
    - name: jnlp
      image: harbor.backbase.eu/internal/inbound-agent-chrome:latest-jdk11
      imagePullPolicy: Always
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      workingDir: /home/jenkins
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /home/jenkins
          name: workspace-volume
      resources:
        limits:
          memory: 16Gi
          cpu: 4
        requests:
          memory: 8Gi
          cpu: 2
      tty: false
      securityContext:
        privileged: true
        runAsUser: 1000
      env:
        - name: JENKINS_URL
          value: https://jenkins.backbase.eu
        - name: HOME
          value: /home/jenkins
